Characteristic.create!([
  {position_id: 2, name: "Pivot Support", description: "Is appropriately available. \r\nDisplays active listening skills. \r\nRepresents the concerns/needs of the report and follows up appropriately. \r\nStays on top of any HR or immigration issues. Identifies effective solutions for pivot.\r\n"},
  {position_id: 2, name: "Pivot Growth", description: "Writes effective regular reviews that drive growth. \r\nCreates alignment between report and company. \r\nHelps advance the pivot in the company (anchor levels, new manager, starting new offices)\r\n"},
  {position_id: 2, name: "Company Support", description: "Approves time sheets \r\nDelivers company messaging \r\nWrites regular reviews on time\r\n"},
  {position_id: 2, name: "Company Growth", description: "Involved in company initiatives or strategic projects. \r\nGrows pivots to achieve business goals (e.g., sales, headcount).\r\nHelps retain pivots.\r\nDesire to understand the business at a higher level\r\n"},
  {position_id: 2, name: "Role Model", description: "Does the right thing. \r\nSets an example for others who do not report to this manager.\r\n"},
  {position_id: 1, name: "Technical Skills", description: ""},
  {position_id: 1, name: "Technical Process", description: ""},
  {position_id: 1, name: "Client Interaction", description: ""},
  {position_id: 1, name: "Teamwork", description: ""},
  {position_id: 1, name: "Larger Context/Project", description: ""},
  {position_id: 1, name: "Feedback", description: ""},
  {position_id: 1, name: "Administrative", description: ""},
  {position_id: 3, name: "Client Support", description: ""},
  {position_id: 3, name: "Company Support", description: ""},
  {position_id: 3, name: "Client Engagement", description: ""},
  {position_id: 3, name: "Manager Support", description: ""},
  {position_id: 3, name: "Manager Growth", description: ""},
  {position_id: 3, name: "Teamwork", description: ""},
  {position_id: 4, name: "Team Support", description: ""},
  {position_id: 4, name: "Client Support", description: ""},
  {position_id: 4, name: "Client Growth", description: ""},
  {position_id: 4, name: "Company Growth", description: ""},
  {position_id: 3, name: "Company Growth", description: ""},
  {position_id: 3, name: "Role Model", description: ""}
])
Position.create!([
  {name: "Developer"},
  {name: "Manager"},
  {name: "Associate Director"},
  {name: "PAT Facilitator"}
])
Rating.create!([
  {value: 3, characteristic_id: 4},
  {value: 4, characteristic_id: 3},
  {value: 4, characteristic_id: 1},
  {value: 4, characteristic_id: 2},
  {value: 4, characteristic_id: 23},
  {value: 4, characteristic_id: 24},
  {value: 4, characteristic_id: 25},
  {value: 4, characteristic_id: 27},
  {value: 4, characteristic_id: 28},
  {value: 4, characteristic_id: 29},
  {value: 4, characteristic_id: 31},
  {value: 4, characteristic_id: 33},
  {value: 4, characteristic_id: 34},
  {value: 3, characteristic_id: 30},
  {value: 3, characteristic_id: 32},
  {value: 3, characteristic_id: 35},
  {value: 4, characteristic_id: 36},
  {value: 3, characteristic_id: 37},
  {value: 3, characteristic_id: 39},
  {value: 3, characteristic_id: 5},
  {value: 2, characteristic_id: 26},
  {value: 3, characteristic_id: 40},
  {value: 3, characteristic_id: 41},
  {value: 4, characteristic_id: 38}
])
